// <auto-generated />
using System;
using KhuVucPhanPhoi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhuVucPhanPhoi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KhuVucPhanPhoi.Models.KhuVuc", b =>
                {
                    b.Property<string>("KhuvucId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhuvucId");

                    b.ToTable("khuVucs");
                });

            modelBuilder.Entity("KhuVucPhanPhoi.Models.NhaPhanPhoi", b =>
                {
                    b.Property<int>("NhaphanphoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhaphanphoiId"));

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuvucId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNpp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("NhaphanphoiId");

                    b.HasIndex("KhuvucId");

                    b.ToTable("nhaPhanPhois");
                });

            modelBuilder.Entity("KhuVucPhanPhoi.Models.NhaPhanPhoi", b =>
                {
                    b.HasOne("KhuVucPhanPhoi.Models.KhuVuc", "Khuvuc")
                        .WithMany("NhaPhanPhois")
                        .HasForeignKey("KhuvucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khuvuc");
                });

            modelBuilder.Entity("KhuVucPhanPhoi.Models.KhuVuc", b =>
                {
                    b.Navigation("NhaPhanPhois");
                });
#pragma warning restore 612, 618
        }
    }
}
