// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaiKhoan.Context;

#nullable disable

namespace TaiKhoan.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240229061121_addPhancapNV")]
    partial class addPhancapNV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaiKhoan.Models.Nhanvien", b =>
                {
                    b.Property<int>("NvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NvId"));

                    b.Property<int?>("ChucvuId")
                        .HasColumnType("int");

                    b.Property<string>("GmailNv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhanhNv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatkhauNv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayLam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TkId")
                        .HasColumnType("int");

                    b.Property<bool?>("TrangthaiNv")
                        .HasColumnType("bit");

                    b.HasKey("NvId");

                    b.ToTable("Nhanviens");

                    b.HasData(
                        new
                        {
                            NvId = 1,
                            ChucvuId = 1,
                            GmailNv = "gmail@gmail.com",
                            HinhanhNv = "avatar.jpg",
                            HoTen = "John Doe",
                            MatkhauNv = "password123",
                            NgayLam = new DateTime(2024, 1, 30, 13, 11, 21, 308, DateTimeKind.Local).AddTicks(6647),
                            NgayTao = new DateTime(2024, 2, 29, 13, 11, 21, 308, DateTimeKind.Local).AddTicks(6630),
                            Sdt = "123456789",
                            TkId = 1,
                            TrangthaiNv = true
                        },
                        new
                        {
                            NvId = 2,
                            ChucvuId = 1,
                            GmailNv = "gmail@gmail.com",
                            HinhanhNv = "avatar.jpg",
                            HoTen = "John Doe",
                            MatkhauNv = "password123",
                            NgayLam = new DateTime(2024, 1, 30, 13, 11, 21, 308, DateTimeKind.Local).AddTicks(6680),
                            NgayTao = new DateTime(2024, 2, 29, 13, 11, 21, 308, DateTimeKind.Local).AddTicks(6679),
                            Sdt = "123456789",
                            TkId = 1,
                            TrangthaiNv = true
                        });
                });

            modelBuilder.Entity("TaiKhoan.Models.PhanCapNV", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("NvID")
                        .HasColumnType("int");

                    b.Property<int>("NvqlID")
                        .HasColumnType("int");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("PhanCapNVs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            NvID = 2,
                            NvqlID = 3,
                            Trangthai = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
