// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Context;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240403125008_deleteRelationKhuvucWithNhanvien")]
    partial class deleteRelationKhuvucWithNhanvien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserService.Models.CapQuyen", b =>
                {
                    b.Property<int>("QuyenTruycapId")
                        .HasColumnType("int");

                    b.Property<int>("ChucvuId")
                        .HasColumnType("int");

                    b.HasKey("QuyenTruycapId", "ChucvuId");

                    b.HasIndex("ChucvuId");

                    b.ToTable("CapQuyen");
                });

            modelBuilder.Entity("UserService.Models.ChucVu", b =>
                {
                    b.Property<int>("ChucvuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChucvuId"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChucvuId");

                    b.ToTable("chucVus");
                });

            modelBuilder.Entity("UserService.Models.KhuVuc", b =>
                {
                    b.Property<string>("KhuvucCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenKhuvuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("KhuvucCode");

                    b.ToTable("khuVucs");
                });

            modelBuilder.Entity("UserService.Models.NhaPhanPhoi", b =>
                {
                    b.Property<int>("nppID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("nppID"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhuvucID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenNPP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("trangthai")
                        .HasColumnType("bit");

                    b.HasKey("nppID");

                    b.HasIndex("KhuvucID");

                    b.ToTable("nhaPhanPhois");
                });

            modelBuilder.Entity("UserService.Models.Nhanvien", b =>
                {
                    b.Property<int>("NvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NvId"));

                    b.Property<int?>("ChucvuId")
                        .HasColumnType("int");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GmailDangnhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GmailNv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GmailQuanly")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HinhanhID")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatkhauNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayLam")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangthaiNv")
                        .HasColumnType("bit");

                    b.Property<bool?>("nguoidung")
                        .HasColumnType("bit");

                    b.Property<int>("nppID")
                        .HasColumnType("int");

                    b.Property<bool?>("quanlyNPP")
                        .HasColumnType("bit");

                    b.Property<bool>("trangThaiTaiKhoan")
                        .HasColumnType("bit");

                    b.HasKey("NvId");

                    b.HasIndex("ChucvuId");

                    b.HasIndex("nppID");

                    b.ToTable("Nhanviens");
                });

            modelBuilder.Entity("UserService.Models.NhomQuyenTruyCap", b =>
                {
                    b.Property<int>("NhomQuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhomQuyenId"));

                    b.Property<string>("TenNq")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NhomQuyenId");

                    b.ToTable("nhomQuyenTruyCap");
                });

            modelBuilder.Entity("UserService.Models.PhanCapNV", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("NvID")
                        .HasColumnType("int");

                    b.Property<int>("NvqlID")
                        .HasColumnType("int");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("PhanCapNVs");
                });

            modelBuilder.Entity("UserService.Models.Quyen", b =>
                {
                    b.Property<int>("QuyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenId"));

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuyenId");

                    b.ToTable("quyens");
                });

            modelBuilder.Entity("UserService.Models.QuyenTruyCap", b =>
                {
                    b.Property<int>("QuyenTruycapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuyenTruycapId"));

                    b.Property<int?>("NhomQuyenId")
                        .HasColumnType("int");

                    b.Property<int?>("QuyenId")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyenTc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuyenTruycapId");

                    b.HasIndex("NhomQuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("quyenTruyCaps");
                });

            modelBuilder.Entity("UserService.Models.CapQuyen", b =>
                {
                    b.HasOne("UserService.Models.ChucVu", "ChucVu")
                        .WithMany("CapQuyens")
                        .HasForeignKey("ChucvuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UserService.Models.QuyenTruyCap", "QuyenTruyCap")
                        .WithMany("CapQuyens")
                        .HasForeignKey("QuyenTruycapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("QuyenTruyCap");
                });

            modelBuilder.Entity("UserService.Models.NhaPhanPhoi", b =>
                {
                    b.HasOne("UserService.Models.KhuVuc", "KhuVuc")
                        .WithMany("NhaPhanPhois")
                        .HasForeignKey("KhuvucID");

                    b.Navigation("KhuVuc");
                });

            modelBuilder.Entity("UserService.Models.Nhanvien", b =>
                {
                    b.HasOne("UserService.Models.ChucVu", "ChucVu")
                        .WithMany("Nhanvien")
                        .HasForeignKey("ChucvuId");

                    b.HasOne("UserService.Models.NhaPhanPhoi", "nhaPhanPhoi")
                        .WithMany("Nhanvien")
                        .HasForeignKey("nppID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");

                    b.Navigation("nhaPhanPhoi");
                });

            modelBuilder.Entity("UserService.Models.QuyenTruyCap", b =>
                {
                    b.HasOne("UserService.Models.NhomQuyenTruyCap", "NhomQuyen")
                        .WithMany("QuyenTruyCaps")
                        .HasForeignKey("NhomQuyenId");

                    b.HasOne("UserService.Models.Quyen", "Quyen")
                        .WithMany("QuyenTruyCaps")
                        .HasForeignKey("QuyenId");

                    b.Navigation("NhomQuyen");

                    b.Navigation("Quyen");
                });

            modelBuilder.Entity("UserService.Models.ChucVu", b =>
                {
                    b.Navigation("CapQuyens");

                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("UserService.Models.KhuVuc", b =>
                {
                    b.Navigation("NhaPhanPhois");
                });

            modelBuilder.Entity("UserService.Models.NhaPhanPhoi", b =>
                {
                    b.Navigation("Nhanvien");
                });

            modelBuilder.Entity("UserService.Models.NhomQuyenTruyCap", b =>
                {
                    b.Navigation("QuyenTruyCaps");
                });

            modelBuilder.Entity("UserService.Models.Quyen", b =>
                {
                    b.Navigation("QuyenTruyCaps");
                });

            modelBuilder.Entity("UserService.Models.QuyenTruyCap", b =>
                {
                    b.Navigation("CapQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
